"""module 5 deployment tables

Adds the `deployments` and `deployment_versions` tables (docs 04). Additive and
reversible: no existing table changes, and dropping both restores the prior
schema. `active_version_id` is a plain nullable UUID -- the route it implies is
owned by the routing module (Module 7), which adds the foreign key.

Revision ID: 2f6b4b3d36ac
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-17

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2f6b4b3d36ac"
down_revision: str | None = "1a2b3c4d5e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=63), nullable=False),
        sa.Column("desired_state", sa.String(length=16), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "desired_state IN ('running', 'stopped')",
            name=op.f("ck_deployments_desired"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
        sa.UniqueConstraint("name", name=op.f("uq_deployments_name")),
    )
    op.create_table(
        "deployment_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "resource_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("image_ref", sa.Text(), nullable=True),
        sa.Column("container_id", sa.String(length=128), nullable=True),
        sa.Column("endpoint", sa.Text(), nullable=True),
        sa.Column("failure", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('building', 'starting', 'ready', 'active', 'failed', 'stopped')",
            name=op.f("ck_deployment_versions_state"),
        ),
        sa.CheckConstraint(
            "attempt > 0", name=op.f("ck_deployment_versions_attempt_positive")
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("fk_deployment_versions_deployment_id_deployments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["packages.id"],
            name=op.f("fk_deployment_versions_package_id_packages"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_versions")),
        sa.UniqueConstraint(
            "deployment_id",
            "package_id",
            "attempt",
            name=op.f("uq_deployment_versions_deployment_id_package_id_attempt"),
        ),
    )
    op.create_index(
        op.f("ix_deployment_versions_deployment_id"),
        "deployment_versions",
        ["deployment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_deployment_versions_deployment_id"), table_name="deployment_versions"
    )
    op.drop_table("deployment_versions")
    op.drop_table("deployments")
    # ### end Alembic commands ###
